version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tynany/frr_exporter
    docker:
      # Whenever the Go version is updated here, .promu.yml, Dockerfile and line 18 of this file should also be updated.
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_promu
      - run: ./promu crossbuild
      - run: ./promu crossbuild tarballs
      - run: ./promu checksum .tarballs
  release:
    working_directory: /go/src/github.com/tynany/frr_exporter
    docker:
      # Whenever the Go version is updated here, .promu.yml, Dockerfile and line 6 of this file should also be updated.
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_promu
      - run: ./promu crossbuild
      - run: ./promu crossbuild tarballs
      - run: ./promu checksum .tarballs
      - run: ./promu release .tarballs
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
